### ISSUE TITLE
BSD-3-Clause, not BSD-4-Clause

### ISSUE THREAD

**Issue by SonOfLilit** [snok/django-guid#105]
Hi,

`LICENSE` contains a standard BSD license, but in `pyproject.toml` it says `BSD-4-Clause`, which confuses our automatic license checker.

If I submit a PR to fix it will it be merged?

Thanks,
Aur

**Comment by JonasKs** [comment]
Hi - I want to change license to MIT. So we can do that now, if you'd like.

**Comment by SonOfLilit** [comment]
That would be lovely. Need help?

**Comment by JonasKs** [comment]
You're welcome to create a PR 😊

**Comment by JonasKs** [comment]
I guess it's easiest through the GitHub GUI. I'll fix it later.

**Comment by JonasKs** [comment]
I've released a new version and a new license. Thank you for the patience.
