### ISSUE TITLE
Integrate with django channels

### ISSUE THREAD

**Issue by joaolrc** [snok/django-guid#121]
Hello

First and foremost, good work here.

It would be nice to integrate with channels.

Have you already figured some way or need some code to be written?

Thanks

**Comment by JonasKs** [comment]
Hi,

Thanks! 

I would expect it to work the exact same? I have never used Django Channels personally, but there's nothing too fancy going on here.

**Comment by joaolrc** [comment]
Probably there is something to be done because middleware does not get triggered by channels connections.

Also there is no request object.

**Comment by JonasKs** [comment]
Happy to accept PR with documentation or implementation, but I won’t be able to assist you, unfortunately.
