### ISSUE TITLE
Pass the GUID of a request to the Celery workers

### ISSUE THREAD

**Issue by JonasKs** [snok/django-guid#33]
Celery tasks triggered by a request will not have the GUID (Correlation-ID) attached to it. Implement a solution to inject the GUID into the Celery logs. 

For Celery tasks that are not triggered by a request, use the `task-id` instead as a GUID.

**Comment by JonasKs** [comment]
In progress by @sondrelg , see #48

**Comment by JonasKs** [comment]
Implemented in #50 . 

Docs and PyPi version bump will follow soon. Creating a new issue for that.

**Comment by JonasKs** [comment]
@rcstanciu & @simkimsia : Django-GUID 3.1.0 now has a `CeleryIntegration`. :)

**Comment by rcstanciu** [comment]
@JonasKs Works like a charm :) Thanks for the heads up! Cheers!
