### ISSUE TITLE
Full UUID as Text

### ISSUE THREAD

**Issue by Mdslino** [snok/django-guid#80]
Why we don't have the option of using the full UUID `776336d4-545e-43e1-bd3b-017794af48e9` instead of the hex output? `776336d4545e43e1bd3b017794af48e9`

**Comment by sondrelg** [comment]
I think I might know the answer, but what's your use case @Mdslino? 🙂

**Comment by Mdslino** [comment]
All the applications in my ecosystem already use the full UUID as GUID, so when someone queries for distributed logs they already search for the full version. I think an option to change that would be nice. I can work on a PR if you want.

**Comment by JonasKs** [comment]
I don’t mind adding that option, PR welcome. 

The GUIDs at my work are all in hex-format, so iirc I just went with that.
